# Generated by Django 5.2.3 on 2025-06-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogrecord',
            name='published_date',
            field=models.DateTimeField(verbose_name='дата публикации'),
        ),
    ]
