# Generated by Django 5.2.3 on 2025-07-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blogrecord_published_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogrecord",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="Опубликовано"),
        ),
    ]
